import type { EmergencyCategoryInfo } from '@/entities/incident'
import type { CallLog } from '@/entities/call'
import type { EmergencyContact } from '@/entities/contact'
import type {
  DashboardStats,
  UserProfile
} from './types'

export const emergencyCategories: EmergencyCategoryInfo[] = [
  {
    id: 'police',
    name: 'Police Emergency',
    description: 'Report crimes, theft, assault, or suspicious activities',
    icon: 'ShieldAlert',
    color: 'text-blue-600 dark:text-blue-400',
    bgColor: 'bg-blue-100 dark:bg-blue-900/30',
    recommendedAgency: 'Royal Thai Police',
  },
  {
    id: 'medical',
    name: 'Medical Emergency',
    description: 'Request ambulance or medical assistance',
    icon: 'Ambulance',
    color: 'text-red-600 dark:text-red-400',
    bgColor: 'bg-red-100 dark:bg-red-900/30',
    recommendedAgency: 'Emergency Medical Services',
  },
  {
    id: 'fire',
    name: 'Fire Emergency',
    description: 'Report fire incidents or request fire rescue',
    icon: 'Flame',
    color: 'text-orange-600 dark:text-orange-400',
    bgColor: 'bg-orange-100 dark:bg-orange-900/30',
    recommendedAgency: 'Fire Department',
  },
  {
    id: 'rescue',
    name: 'Rescue Team',
    description: 'Request rescue operations for emergencies',
    icon: 'LifeBuoy',
    color: 'text-emerald-600 dark:text-emerald-400',
    bgColor: 'bg-emerald-100 dark:bg-emerald-900/30',
    recommendedAgency: 'National Rescue Team',
  },
  {
    id: 'flood',
    name: 'Flood Disaster',
    description: 'Report flooding or request evacuation assistance',
    icon: 'Waves',
    color: 'text-cyan-600 dark:text-cyan-400',
    bgColor: 'bg-cyan-100 dark:bg-cyan-900/30',
    recommendedAgency: 'Disaster Prevention Center',
  },
  {
    id: 'road-accident',
    name: 'Road Accident',
    description: 'Report traffic accidents or road emergencies',
    icon: 'Car',
    color: 'text-amber-600 dark:text-amber-400',
    bgColor: 'bg-amber-100 dark:bg-amber-900/30',
    recommendedAgency: 'Highway Police',
  },
]

export const mockEmergencyContacts: EmergencyContact[] = [
  {
    id: '1',
    agencyName: 'Central Police Station',
    phoneNumber: '191',
    category: 'police',
    province: 'Bangkok',
    district: 'Pathum Wan',
    distance: 1.2,
    status: 'active',
    is24Hours: true,
    coordinates: { latitude: 13.7465, longitude: 100.5331 },
  },
  {
    id: '2',
    agencyName: 'Emergency Medical Services',
    phoneNumber: '1669',
    category: 'medical',
    province: 'Bangkok',
    district: 'Pathum Wan',
    distance: 0.8,
    status: 'active',
    is24Hours: true,
    coordinates: { latitude: 13.7478, longitude: 100.5351 },
  },
  {
    id: '3',
    agencyName: 'Fire Station District 1',
    phoneNumber: '199',
    category: 'fire',
    province: 'Bangkok',
    district: 'Pathum Wan',
    distance: 2.1,
    status: 'active',
    is24Hours: true,
    coordinates: { latitude: 13.7442, longitude: 100.5298 },
  },
  {
    id: '4',
    agencyName: 'National Rescue Foundation',
    phoneNumber: '1554',
    category: 'rescue',
    province: 'Bangkok',
    district: 'Pathum Wan',
    distance: 3.5,
    status: 'active',
    is24Hours: true,
    coordinates: { latitude: 13.7501, longitude: 100.5402 },
  },
  {
    id: '5',
    agencyName: 'Disaster Prevention Center',
    phoneNumber: '1784',
    category: 'flood',
    province: 'Bangkok',
    district: 'Pathum Wan',
    distance: 1.8,
    status: 'active',
    is24Hours: true,
    coordinates: { latitude: 13.7489, longitude: 100.5367 },
  },
]

export const mockCallLogs: CallLog[] = [
  {
    id: '1',
    date: new Date('2024-01-15T10:30:00'),
    incidentType: 'medical',
    agency: mockEmergencyContacts[1],
    location: {
      latitude: 13.7563,
      longitude: 100.5018,
      province: 'Bangkok',
      district: 'Pathum Wan',
      accuracy: 15,
      lastUpdated: new Date('2024-01-15T10:30:00'),
    },
    status: 'connected',
    notes: 'Ambulance dispatched successfully',
  },
  {
    id: '2',
    date: new Date('2024-01-14T15:45:00'),
    incidentType: 'police',
    agency: mockEmergencyContacts[0],
    location: {
      latitude: 13.7563,
      longitude: 100.5018,
      province: 'Bangkok',
      district: 'Pathum Wan',
      accuracy: 10,
      lastUpdated: new Date('2024-01-14T15:45:00'),
    },
    status: 'connected',
    notes: 'Patrol unit responded',
  },
  {
    id: '3',
    date: new Date('2024-01-13T08:20:00'),
    incidentType: 'fire',
    agency: mockEmergencyContacts[2],
    location: {
      latitude: 13.7563,
      longitude: 100.5018,
      province: 'Bangkok',
      district: 'Pathum Wan',
      accuracy: 20,
      lastUpdated: new Date('2024-01-13T08:20:00'),
    },
    status: 'no-answer',
    notes: 'Called back after 5 minutes',
  },
]

export const mockDashboardStats: DashboardStats = {
  totalCallsToday: 1247,
  activeIncidents: 23,
  totalAgencies: 856,
  avgResponseTime: 4.2,
  callsByCategory: {
    'police': 312,
    'medical': 456,
    'fire': 89,
    'rescue': 67,
    'flood': 45,
    'road-accident': 178,
  },
  callsByProvince: {
    'Bangkok': 456,
    'Chiang Mai': 123,
    'Phuket': 89,
    'Chonburi': 156,
    'Khon Kaen': 78,
    'Songkhla': 67,
    'Nakhon Ratchasima': 89,
    'Other': 189,
  },
  successRate: 94.5,
}

export const mockUserProfile: UserProfile = {
  id: '1',
  name: 'John Doe',
  phone: '+66 81 234 5678',
  emergencyContacts: [
    { id: '1', name: 'Jane Doe', phone: '+66 82 345 6789', relationship: 'Spouse' },
    { id: '2', name: 'Bob Smith', phone: '+66 83 456 7890', relationship: 'Parent' },
    { id: '3', name: 'Alice Johnson', phone: '+66 84 567 8901', relationship: 'Sibling' },
  ],
  settings: {
    language: 'en',
    notifications: true,
    offlineMode: false,
    darkMode: false,
  },
}

export const provinces = [
  'Bangkok',
  'Chiang Mai',
  'Chiang Rai',
  'Chonburi',
  'Khon Kaen',
  'Krabi',
  'Nakhon Ratchasima',
  'Nonthaburi',
  'Pathum Thani',
  'Phuket',
  'Samut Prakan',
  'Songkhla',
  'Surat Thani',
  'Udon Thani',
]

export const districts: Record<string, string[]> = {
  'Bangkok': ['Pathum Wan', 'Chatuchak', 'Sukhumvit', 'Silom', 'Siam', 'Ratchathewi'],
  'Chiang Mai': ['Mueang', 'San Sai', 'Hang Dong', 'Mae Rim', 'San Kamphaeng'],
  'Phuket': ['Mueang Phuket', 'Kathu', 'Thalang'],
  'Chonburi': ['Mueang Chonburi', 'Pattaya', 'Bang Lamung', 'Si Racha'],
}
